### ISSUE TITLE
Adding optional a href link for images

### ISSUE THREAD

**Issue by angelacastaneda** [MangoUmbrella/goldmark-figure#4]
Hey big fan of your package. I used to always write insanity in pandoc markdown to get the functionality your code provides:

```md
![figcaption](/path/to/img.jpg `title'){alt="alt text"}
```

anyways, I was hoping you could add a feature to optionally toggle a hyperlink to the image itself, e.g.

```md
![alt text](/path/to/img.jpg "title")
figcaption
```

generates

```html
<figure>
  <a href="/path/to/img.jpg">
    <img src="/path/to/img.jpg" alt="alt text" title="title"/>
  </a>
  <figcaption>figcaption</figcaption>
</figure>
```

That way you can just click on an image to zoom in. Thanks again for the cool package.

**Comment by yilei** [comment]
Thank you for the FR @angelacastaneda!

I just published a new version v1.1.0 to optionally add an image link, see [instructions](https://github.com/MangoUmbrella/goldmark-figure/?tab=readme-ov-file#option-to-add-link-to-the-image).

Feel free to open another issue if you encounter any problems.
